name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Create app_env file from GitHub Secrets
        run: |
          mkdir -p assets
          echo "APP_ID=${{ secrets.APP_ID }}" > assets/app_env
          echo "REST_KEY=${{ secrets.REST_KEY }}" >> assets/app_env
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> assets/app_env

      - name: Build Flutter Web and copy app_env
        run: |
          flutter build web --release --base-href "/2023tm93771-cross-platform-assignment/"
          cp assets/app_env build/web/assets/  # Critical fix

      - name: Add .nojekyll and security headers
        run: |
          touch build/web/.nojekyll
          echo "/assets/app_env" >> build/web/_headers
          echo "  X-Robots-Tag: none" >> build/web/_headers
          echo "  Cache-Control: no-store" >> build/web/_headers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true