name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Create .env file from GitHub Secrets
        run: |
          mkdir -p assets  # Create assets directory if it doesn't exist
          echo "APP_ID=${{ secrets.APP_ID }}" > assets/.env
          echo "REST_KEY=${{ secrets.REST_KEY }}" >> assets/.env
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> assets/.env

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/2023tm93771-cross-platform-assignment/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true